language: python
python:
  - 3.8
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  - pip install -e .
  - pip install pytest-travis-fold
script: py.test # run tests
after_success:
  - codecov # submit coverage